# Generated by Django 5.1 on 2024-08-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player1', models.CharField(max_length=30)),
                ('Player2', models.CharField(blank=True, max_length=30)),
                ('gameDate', models.DateTimeField()),
                ('gameEnded', models.BooleanField(default=False)),
                ('scorePlayer1', models.PositiveBigIntegerField()),
                ('scorePlayer2', models.PositiveBigIntegerField()),
                ('winner', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
