# Generated by Django 5.0.7 on 2024-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Language',
            field=models.CharField(choices=[('FR', 'French'), ('EN', 'English'), ('NL', 'Dutch')], default='EN', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='twoFA',
            field=models.CharField(choices=[('NONE', 'None'), ('MAIL', 'Mail'), ('APK', 'APK')], default='NONE', max_length=4),
        ),
    ]
