# Generated by Django 5.0.7 on 2024-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_motdepasse_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastTimeOnline',
            field=models.DateTimeField(),
        ),
    ]
