# Generated by Django 5.0.7 on 2024-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_lasttimeonline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
