# Generated by Django 5.0.7 on 2024-08-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('MotDePasse', models.CharField(blank=True, max_length=1000)),
                ('Avatar', models.CharField(max_length=1000)),
                ('key2FA', models.CharField(max_length=100)),
                ('lastTimeOnline', models.DateField()),
                ('pongLvl', models.PositiveBigIntegerField()),
                ('tetrisLvl', models.PositiveBigIntegerField()),
            ],
        ),
    ]
